# Generated by Django 2.1 on 2020-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='56', max_length=50, verbose_name='Телефон пользователя'),
            preserve_default=False,
        ),
    ]
