# Generated by Django 2.1 on 2020-09-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100000, null=True, verbose_name='Текст комментария')),
                ('start_date', models.DateField(verbose_name='Время создания комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_network.Post')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='social_network.Comments')),
                ('user_nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_network.UserInfo')),
            ],
        ),
    ]
