# Generated by Django 2.1 on 2020-09-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='access_status',
            field=models.BooleanField(default=True, verbose_name='Статус доступа к приложению'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_post_status',
            field=models.BooleanField(default=True, verbose_name='Возможность создавать посты'),
        ),
    ]
