# Generated by Django 2.1 on 2020-09-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20200924_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг поста'),
        ),
    ]
